version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend-growpromise
    restart: always
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max_old_space_size=4096  
    mem_limit: 4g  
    networks:
      - growpromise-network

networks:
  growpromise-network:
    external: true